language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-21.0.2
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - nvm install node
    - echo no | npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable

before_script:
    - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator

script:
    - npm run cisetup
    - npm run citest
